
server:
  port: 8081
spring:
  profiles:
  server:
  application:
    name: AppointmentService
    event:
      incoming:
        topic:
          reminder: publishReminder
          restock: vaccineInventory
      outgoing:
        topic:
          shotAdministrated: shotAdministrated


  datasource:
    url: jdbc:mysql://localhost:3306/appointments_service
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: appointment-listener
      topic:
        name: vaccineInventory,publishReminder
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retries: 10
